---
gke_cluster_test1:
  cluster_name : "test-gke-cluster-1"
  location : "europe-west1"
  machine_type : "e2-medium"
  logging_service : "logging.googleapis.com/kubernetes"
  monitoring_service : "monitoring.googleapis.com/kubernetes"
  oauth_scopes : "https://www.googleapis.com/auth/cloud-platform"
  #service_account_email : "test-terraform1@myproject-7777777.iam.gserviceaccount.com"
  node_pools : 
    - name : "test-gke-node-pool-1"
      machine_type : "e2-medium"
      initial_node_count : 1
      disk_size_gb : 10
      disk_type : 'pd-standard'
      preemptible : true
      service_account_email : "test-terraform1@myproject-7777777.iam.gserviceaccount.com"
      autoscaling :
        min_node_count : 1
        max_node_count : 2
    - name: "test-gke-node-pool-2"
      machine_type : "e2-medium"
      initial_node_count : 1
      disk_size_gb : 10
      disk_type : 'pd-standard'
      preemptible : true
      service_account_email : "test-terraform1@myproject-7777777.iam.gserviceaccount.com"
      autoscaling :
        min_node_count : 1
        max_node_count : 2
